#!/bin/bash
echo "************ Cronny Started MINUTELY ***************"
hour=$(date +%H)
echo $hour;

if [ $(($hour % 2)) -eq 0 ]; then
    node ${OPENSHIFT_REPO_DIR}/cron/get-tracking.js
fi
echo "************ Cronny Executed ***************"

